### ISSUE TITLE
support spaces in path names

### ISSUE THREAD

**Issue by jefflembeck** [npm/marky-markdown#195] opened 2016-06-09 22:50 UTC
See badges at the top of https://npmjs.com/package/johnny-five

![johnny-five 2016-06-09 15-49-57](https://cloud.githubusercontent.com/assets/109699/15949114/db6c7f5a-2e59-11e6-823b-5f88a117b411.png)

Not sure if it's the `.svg` extension or what.

The current README.md on latest has:

`[![Gitter](https://badges.gitter.im/Join Chat.svg)](https://gitter.im/rwaldron/johnny-five?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)`

**Comment by ashleygwilliams** [comment] 2016-06-10 17:57
hrm, i wonder if it is the space is the img path

**Comment by ashleygwilliams** [comment] 2016-06-10 17:58
i'm seeing

<img width="392" alt="screen shot 2016-06-10 at 10 58 27 am" src="https://cloud.githubusercontent.com/assets/1163554/15973832/5074a7d2-2efa-11e6-868a-192912a90266.png">
<img width="563" alt="screen shot 2016-06-10 at 10 58 35 am" src="https://cloud.githubusercontent.com/assets/1163554/15973833/5075dab2-2efa-11e6-8380-0bf16058c236.png">

**Comment by revin** [comment] 2016-06-10 18:12
Good call, spaces aren't strict CommonMark:
http://spec.commonmark.org/0.25/#link-destination

On Friday, June 10, 2016, ashley williams <notifications@github.com> wrote:

> i'm seeing
>
> [image: screen shot 2016-06-10 at 10 58 27 am]
> <https://cloud.githubusercontent.com/assets/1163554/15973832/5074a7d2-2efa-11e6-868a-192912a90266.png>
> [image: screen shot 2016-06-10 at 10 58 35 am]
> <https://cloud.githubusercontent.com/assets/1163554/15973833/5075dab2-2efa-11e6-8380-0bf16058c236.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/npm/marky-markdown/issues/195#issuecomment-225252207>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAFyggXJ2twPCYOFQKzzjw0NT6vDR6gBks5qKaXhgaJpZM4IyexH>
> .
>


-- 
--
Revin Guillen
rg@sevenite.com

**Comment by revin** [comment] 2016-06-10 18:13
So to support this we could probably do a markdown-it plugin or something

On Friday, June 10, 2016, Revin Guillen <rg@sevenite.com> wrote:

> Good call, spaces aren't strict CommonMark:
> http://spec.commonmark.org/0.25/#link-destination
>
> On Friday, June 10, 2016, ashley williams <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> i'm seeing
>>
>> [image: screen shot 2016-06-10 at 10 58 27 am]
>> <https://cloud.githubusercontent.com/assets/1163554/15973832/5074a7d2-2efa-11e6-868a-192912a90266.png>
>> [image: screen shot 2016-06-10 at 10 58 35 am]
>> <https://cloud.githubusercontent.com/assets/1163554/15973833/5075dab2-2efa-11e6-8380-0bf16058c236.png>
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/npm/marky-markdown/issues/195#issuecomment-225252207>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AAFyggXJ2twPCYOFQKzzjw0NT6vDR6gBks5qKaXhgaJpZM4IyexH>
>> .
>>
>
>
> --
> --
> Revin Guillen
> rg@sevenite.com <javascript:_e(%7B%7D,'cvml','rg@sevenite.com');>
>
>

-- 
--
Revin Guillen
rg@sevenite.com

**Comment by ashleygwilliams** [comment] 2016-06-10 18:37
https://github.com/markdown-it/markdown-it/issues/72

**Comment by ashleygwilliams** [comment] 2016-06-10 18:41
this is not a bug. it is a feature request. marking as such.

**Comment by revin** [comment] 2016-07-08 17:54
Looked into this some more; looks like the change we need is to remove the `|| isSpace(code)` clause from https://github.com/markdown-it/markdown-it/blob/master/lib/helpers/parse_link_destination.js#L25. This part of `markdown-it` isn't really designed for easy pluggability, so I guess what we'd need to do is completely duplicate/replace the `link` rule and replace [line 54](https://github.com/markdown-it/markdown-it/blob/master/lib/rules_inline/link.js#L54) with a call to our own custom version that allows spaces.

**Comment by sjking** [comment] 2016-10-27 01:25
Please see PR #280

**Comment by revin** [comment] 2017-01-10 00:40
fixed in #280

**Closed by revin** 2017-01-10 00:40 UTC
Labels: github feature request, hacktoberfest, PR attached, question
