### ISSUE TITLE
Ampersands in package descriptions are HTML encoded.

### ISSUE THREAD

**Issue by lewiscowper** [npm/marky-markdown#124] opened 2016-01-22 12:30 UTC
![screen shot 2016-01-22 at 13 13 47](https://cloud.githubusercontent.com/assets/593574/12510428/099e6090-c10a-11e5-8587-c67a956d6c20.png)

I'm not sure exactly where the problem lies, I found the following function in the website repository: https://github.com/npm/newww/blob/c4818328d5e936f359b587d340d8a3b821026672/presenters/package.js#L173

which led me to:

https://github.com/npm/marky-markdown/blob/master/lib/packagize.js#L48

There's a lot of conditional logic I'm not familiar with used here, but I'm assuming that at some point we return the description as-is, instead of un-encoding it and rendering it appropriately.

**Comment by revin** [comment] 2016-01-22 15:35
If I run marky standalone against this README, the description renders correctly, so I think this is a newww bug. I'm far from a handlebars expert, but I *think* the issue is that once marky has processed the description, https://github.com/npm/newww/blob/master/templates/package/show.hbs#L13 is double encoding it, so `{{{description}}}` (with three sets of braces rather than two) is the fix.

**Comment by ashleygwilliams** [comment] 2016-01-22 15:36
lol i was *just* about to say that
<img width="571" alt="screen shot 2016-01-22 at 10 36 30 am" src="https://cloud.githubusercontent.com/assets/1163554/12514989/0c8fd31c-c0f4-11e5-9dfb-4df0412359a6.png">

**Comment by ashleygwilliams** [comment] 2016-01-22 15:37
closing and refiling on newww

**Closed by ashleygwilliams** 2016-01-22 15:37 UTC
Labels: bug
