### ISSUE TITLE
Incorrect links are being created

### ISSUE THREAD

**Issue by jefflembeck** [npm/marky-markdown#146] opened 2016-02-08 20:09 UTC
See: https://github.com/npm/newww/issues/1842

The README for the package has

`*Readme.md*` in it, this is rendering as a link on the package page instead of just emphasizing the text.

editing title and issue to be more correct for the issue at hand.

**Comment by wooorm** [comment] 2016-02-08 20:27
emphasis* :wink:

markdown-it’s auto-linker detects `readme.md` as a domain from Moldova (`.md`), it seems: [demo](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22readme.md%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

**Comment by ashleygwilliams** [comment] 2016-02-08 20:39
ruh roh. we'll want to see if we can make this an option in `markdown-it` before we patch in marky.

**Comment by ashleygwilliams** [comment] 2016-02-08 20:40
i am p sure this does not have to do with the `<em>` but rather the detection of that file name. this actually happens for all `.md` words. see: https://www.npmjs.com/package/test-test-test-test

**Comment by wooorm** [comment] 2016-02-08 20:44
Fun fact: *readme.md* is in fact a real site (I wish I thought of that). so if you want to disable this behaviour I think all non-protocol and non-www domains should *not* be linked? (GitHub doesn’t link either)

**Comment by ashleygwilliams** [comment] 2016-02-08 20:48
we are following gh-rendering for product, so i think that is a great idea
would really like to get markdown-it to do that, but we'll see. anyone feel like filing? otherwise i'll get to it at some point today.

**Comment by revin** [comment] 2016-02-08 22:15
markdown-it uses [linkify-it](https://github.com/markdown-it/linkify-it) to do this, and it [looks like](https://github.com/markdown-it/markdown-it#linkify) we can turn TLDs off one by one if we want (or otherwise do bulk configuration of the LinkifyIt behavior). Would turning off `.md` be enough, or is there some more thorough test we can base marky's behavior on?

**Comment by revin** [comment] 2016-02-08 22:22
OK yes, inserting
```js
  parser.linkify.tlds('.md', false)
```
right above https://github.com/npm/marky-markdown/blob/master/lib/render.js#L57 does the trick for `.md` (non-)links, so it looks like we can control this sufficiently ourselves, and the final question is just what exactly what we want the behavior to be.

**Comment by fibo** [comment] 2016-02-10 20:03
I.m.h.o. the markdown parser should parse outside in, I mean *http://example.org* should be parsed as in this comment itself ... let me push the green button to see it :)

**Comment by ashleygwilliams** [comment] 2016-02-10 20:05
hi @fibo! marky allows the behavior you are describing. the unwanted behavior is that README.md is parsed as a link, which you can see here in GitHub-land, is not.

**Comment by ashleygwilliams** [comment] 2016-02-10 20:06
hey @revin want to start with a patch that just does that? i think we might have to wait and see what other bugs we run into. this is the only one i've seen reported thus far

**Comment by revin** [comment] 2016-02-10 20:09
@ashleygwilliams sure thing. Do we just want to exclude `.md` specifically, or all two-letter TLDs, or anything lacking a protocol or www (which is what @wooorm suggested, right?)? I see in [npm/newww#1860](https://github.com/npm/newww/issues/1860) that `.name` is being included as well, which doesn't seem correct.

**Comment by ashleygwilliams** [comment] 2016-02-10 21:14
hrm, let's do `.md` and `.name` for now, and then let's try to figure out what the GitHub behavior is and just copy that? while @wooorm's suggesting makes a bunch of sense to me, it might be conflict with GitHub parity? i want to avoid regressions until we can be sure. i also want to get this out as a patch ASAP :)

thanks so much!

**Comment by revin** [comment] 2016-02-10 21:17
ok, I was literally seconds from hitting the submit button on one that disables all raw hostnames, so I'll submit that one and do the super specific one immediately after that

**Comment by ashleygwilliams** [comment] 2016-02-10 21:18
ok cool. i am probably being too cautious, heh :sweat_smile:

**Comment by revin** [comment] 2016-02-10 21:27
#152 for the .md/.name specific one

**Comment by ashleygwilliams** [comment] 2016-02-10 21:27
<3

**Comment by fibo** [comment] 2016-02-11 07:22
Hi @ashleygwilliams , I mean *example.org* and *readme.md* (in previous comment I prepended an http that is not what I mean) should not be parsed as links as the markdown parser used to render this comment itself. Blacklisting few domains will just **move** the problem. The solution would be improve the regex that recognize the URLs, since *foo.md* is not an URL while *http://foo.md* it is.

However if this solves https://github.com/npm/newww/issues/1842  is great!
(not so polite for Moldavian folks, but now I know a new domain hack 🎶)

**Comment by revin** [comment] 2016-02-11 07:40
@fibo thanks; I think we're on the same page here. The blacklist is a temporary solution that will cover the most common sources of this error, and in #151 we're working on a more complete solution. One of my comments on that PR is there to test how GH renders various cases, so if you have ideas for more entries for that list, by all means please feel free to add whatever you can think of.

**Comment by revin** [comment] 2016-07-07 23:24
substantial progress (though not absolutely perfect GH parity yet) in #151; closing since it covers the common cases here

**Closed by revin** 2016-07-07 23:24 UTC
Labels: bug, PR attached
